trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: COURSIER_CACHE
    value: $(Pipeline.Workspace)/.coursier
  - name: IVY_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.ivy2

steps:
  - task: Cache@2
    inputs:
      key: 'sbt | $(Agent.OS) | **/build.sbt | project/Dependencies.scala'
      restoreKeys: |
        sbt | $(Agent.OS) | **/build.sbt
        sbt | $(Agent.OS)
        sbt
      path: $(Pipeline.Workspace)/.ivy2
  - task: Cache@2
    inputs:
      key: 'sbt | $(Agent.OS) | **/build.sbt | project/Dependencies.scala'
      restoreKeys: |
        sbt | $(Agent.OS) | **/build.sbt
        sbt | $(Agent.OS)
        sbt
      path: $(Pipeline.Workspace)/.coursier
  - script: sbt ci
    displayName: "Run sbt tests"